name: Generate snake animation

on:
  schedule:
    - cron: "0 */12 * * *" 
  workflow_dispatch: # Tombol untuk menjalankan manual
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Generate snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}

          outputs: |
            dist/snake.svg?palette=github-dark
            dist/snake-dark.svg?palette=github-dark&color_snake=cyan
            dist/snake.gif?palette=github-dark
            
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
